# Generated by Django 5.1 on 2024-08-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subemail',
            name='is_active',
        ),
    ]
