# Generated by Django 5.1 on 2024-08-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_subemail_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subemail',
            old_name='email',
            new_name='subemail',
        ),
    ]
